name: Main Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install

      # Run unit tests with coverage report
      - name: Run unit tests
        run: npm run test:unit  # No extra --coverage
        env:
          CI: true

      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright install-deps # Installs Playwright dependencies
          npx playwright test
        env:
          CI: true

      # Generate and upload coverage report
      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      # Perform a build check
      - name: Build project
        run: npm run build
